version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 835080864477.dkr.ecr.ap-northeast-2.amazonaws.com/beming/about
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t nest-app .
      - docker tag nest-app 835080864477.dkr.ecr.ap-northeast-2.amazonaws.com/beming/about/nest-app
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 835080864477.dkr.ecr.ap-northeast-2.amazonaws.com/beming/about/nest-app
