version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 835080864477.dkr.ecr.ap-northeast-2.amazonaws.com/beming/about
  build:
    commands:
      - echo Building the Docker image...
      - >
        docker build
        --build-arg MONGODB_URI=$MONGODB_URI
        --build-arg cryptoKey=$cryptoKey
        --build-arg PAPERTRAIL_API_TOKEN=$PAPERTRAIL_API_TOKEN
        --build-arg AWS_KEY=$AWS_KEY
        --build-arg AWS_ACCESS_KEY=$AWS_ACCESS_KEY
        --build-arg PUBLIC_KEY=$PUBLIC_KEY
        --build-arg PRIVATE_KEY=$PRIVATE_KEY
        --build-arg NEW_RELIC_APP_NAME=$NEW_RELIC_APP_NAME
        --build-arg NEW_RELIC_LICENSE_KEY=$NEW_RELIC_LICENSE_KEY
        --build-arg NEW_RELIC_LOG=$NEW_RELIC_LOG
        --build-arg NEW_RELIC_NO_CONFIG_FILE=$NEW_RELIC_NO_CONFIG_FILE
        --build-arg NEW_RELIC_ENABLED=$NEW_RELIC_ENABLED
        -t nest-app .
      - docker tag nest-app 835080864477.dkr.ecr.ap-northeast-2.amazonaws.com/beming/about
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 835080864477.dkr.ecr.ap-northeast-2.amazonaws.com/beming/about
artifacts:
  files:
    - appspec.yml
    - scripts/** # EC2에서 실행할 스크립트 포함
