@jwt = eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..nptdCxy19SoAz-yT.8z6AltSTvrA8RfxZCneRnRC3arHk1G_1TipQ8hbipejLivotpfnbwLuwRrsX1iOtsGwhGfBda_2IEwM77sAPQU6wy90vI3HcX5PlfZ9R3hi3bjVkW3PGhG9g9hTrOBSLGsB4c461G5Y4Mqf-PtyLb1lVoPcUOeWmHKXnEen2TlhljTIx5xq7jJQRS50IQ5NdqPvt5y2lmHO8LPBnz1C2SBS-2GRPeDDpJt3MZkDKadTOMpAcnrDnxdPmhmOK1DTD0a_Oha09E0X4L4uahcx0JgkVQkh7TYkZVaTdkgmYuripgpZ2yQdYEMCjM3npr_a1cv22Dq2ahwm9NizxiZnN-JrRFzMXEr5vt9wsi-OcuAGRR8BTPxbf9wDNZSZo-IfAFtsq8Fek2m8BFtTP-22v2rn1K7DY0LmffO4eyZr1hfO9zUqtNtNk-wEs8L15MaDPILsOpstIJ0X-vPdqy2MyflmsN26kOvfLFghBbQ2x9Mj05n0VgfdFgBFJ7riFixDgdxxoNgyGcLWzPZyFplr81HJyErhpytLjMAeW6TPUOBBmccFyxtItnYw0Za4-JLIkU1Jq48xxsIkvq_oMmOgJbTrvqtN6chLyC20Vrd88V-Cz9Iac1GPktj5LZ4M_YdspIXff_FHYEZqXCYIBnyo62JOESxRmpOMrvMU.2WeDaJjtyx61Q050ffvEDw

###
GET http://localhost:3001/vote/arrived?startDay=2024-09-01&endDay=2024-09-10
Content-Type: application/json
Authorization: Bearer {{jwt}}

###
GET http://localhost:3001/vote/participationCnt?startDay=2024-09-01&endDay=2024-09-10&location=수원
Content-Type: application/json
Authorization: Bearer {{jwt}}

###
GET http://localhost:3001/vote/2024-09-08?location=수원
Content-Type: application/json
Authorization: Bearer {{jwt}}

###
POST http://localhost:3001/vote/2024-09-08
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "place": "62e5d6e0e098c232c05c3d3f",
    "subPlace": ["6437e9d7ab537b843c6143ac"],
    "start": "2024-09-08T06:00:00.000+00:00",
    "end": "2024-09-08T09:00:00.000+00:00",
    "memo": ""
}

###
PATCH http://localhost:3001/vote/2024-09-08
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "start": "2024-09-09T06:00:00.000+00:00",
    "end": "2024-09-09T09:00:00.000+00:00"
}

###
DELETE http://localhost:3001/vote/2024-09-08
Content-Type: application/json
Authorization: Bearer {{jwt}}

###
GET http://localhost:3001/vote/2024-09-08/week?location=수원
Content-Type: application/json
Authorization: Bearer {{jwt}}

###
POST http://localhost:3001/vote/2024-09-08/absence
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "message": "helo"
}

###
GET http://localhost:3001/vote/2024-09-08/absence
Content-Type: application/json
Authorization: Bearer {{jwt}}

###
GET http://localhost:3001/vote/2024-09-08/arrived
Content-Type: application/json
Authorization: Bearer {{jwt}}

###
PATCH http://localhost:3001/vote/2024-09-08/arrived
Content-Type: application/jsond
Authorization: Bearer {{jwt}}

{
    "memo": "hello"
}

###
PATCH http://localhost:3001/vote/2024-09-08/confirm
Content-Type: application/json
Authorization: Bearer {{jwt}}

###
PATCH http://localhost:3001/vote/2024-09-08/dismiss
Content-Type: application/json
Authorization: Bearer {{jwt}}

###
GET http://localhost:3001/vote/2024-09-08/start
Content-Type: application/json
Authorization: Bearer {{jwt}}

###
PATCH http://localhost:3001/vote/2024-09-08/comment
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "comment": "arrived"
}