export const DB_SCHEMA = {
  ACCOUNT: 'Account',
  ACCOUNCEMENT: 'Announcement',
  CHAT: 'Chat',
  COLLECTION: 'collection',
  DAILYCHECK: 'DailyCheck',
  FEED: 'Feed',
  GATHER: 'Gather',
  GIFT: 'GiftModel',
  GROUPSTUDY: 'GroupStudy',
  LOG: 'Log',
  NOTICE: 'Notice',
  PAYMENT: 'Payment',
  PLACE: 'Place',
  PROMOTION: 'Promotion',
  REALTIME: 'Realtime',
  REGISTER: 'Registered',
  REQUEST: 'Request',
  SQUARE: 'SecretSquare',
  USER: 'User',
  VOTE: 'vote2',
  WEBPUSH: 'NotificationSub',
};
